# Generated by Django 5.1.3 on 2024-11-23 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stafftakesaction',
            options={'managed': False},
        ),
    ]
