# Generated by Django 5.1.3 on 2024-11-23 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_stafftakesaction_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stafftakesaction',
            options={},
        ),
    ]
